### ISSUE TITLE
官网和本地安装页面访问都很卡，是否有待优化？还是laravel11环境原因，是否有优化建议。

### ISSUE THREAD

**Issue by qiacoucc** [owl-admin/demo-site#4]
![很卡](https://github.com/owl-admin/demo-site/assets/38834636/0a4b6390-d055-44c9-816f-9cb9a320b140)

![很卡2](https://github.com/owl-admin/demo-site/assets/38834636/05f5163d-ba54-4ae7-9b70-89f6a709efa2)

**Comment by slowlyo** [comment]
![image](https://github.com/owl-admin/demo-site/assets/94038215/e03a9789-9c43-4d97-98bc-161271711330)

本地挺快的嘛 :joy:

检查一下你自己的本地环境

演示环境慢是因为服务器配置比较拉跨, 访问量稍微大一点就慢的不行
